### ISSUE TITLE
Clean UP & Dockerization eos7a04

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos7a04#6]

**Comment by HellenNamulinda** [comment]
The Model Test on push [failed](https://github.com/ersilia-os/eos7a04/actions/runs/5424663348/jobs/9864343780#step:10:638). And besides the rdkit package conflicts, there is an issue with the model path which I'm to correct with absolute path.
```
/home/runner/eos/repository/eos7a04/20230630163033_E3F475/eos7a04/artifacts/framework/run_cddd.py: line 9: from: command not found
/home/runner/eos/repository/eos7a04/20230630163033_E3F475/eos7a04/artifacts/framework/run_cddd.py: line 10: syntax error near unexpected token `('
/home/runner/eos/repository/eos7a04/20230630163033_E3F475/eos7a04/artifacts/framework/run_cddd.py: line 10: `_default_model_dir = os.path.join(DEFAULT_DATA_DIR, 'default_model')'
```

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron,
There is an issue that I'm yet to fix. the model uses tensorflow 1.10 which requires numpy(<=1.14.5,  >=1.13). Since there is no specific [version of rdkit ](https://github.com/jrwnter/cddd) recommended for the model, I though updating it would resolve the conflicts, but it didn't(versions 2021.3.2+ require` numpy>=1.19`, and those below required numpy==1.12.0. somehow numpy==1.14.5 which is installed ends up not being seen. For this, runing the model using the python predict file still fails
```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "predict.py", line 8, in <module>
    from cddd.preprocessing import preprocess_smiles
  File "/home/hellenah/Outreachy/eos7a04/model/framework/cddd/preprocessing.py", line 5, in <module>
    from rdkit.Chem.SaltRemover import SaltRemover
  File "/home/hellenah/anaconda3/envs/eos7a04/lib/python3.6/site-packages/rdkit/Chem/__init__.py", line 20, in <module>
    from rdkit.Chem import rdchem
SystemError: initialization of rdchem raised unreported exception
```
My last option is to dowgrade conda to install rdkit 2019.3.1 which is specified in the docker file. Though this means that we won't have the arm64 docker image(aarch supports later versions, and tensorflow is has already posed a restriction). 

I will update you if I fail, after trying all the ideas I have.
Thanks!

**Comment by GemmaTuron** [comment]
Thanks for these explanations @HellenNamulinda 

I agree it is annoying we cannot find a compatible version of rdkit and numpy. When you say numpy 1.14.5 is not seen, might it be we need to install it last so to avoid downgrading or upgrading when installing other packages? But I see the sequence of installs in the Docker file is right.
If you follow it and activate the environment, which version of numpy you get?

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron,
Following that order, it causes pip error, and running the code, that's when I get the error of `ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'`
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rdkit-pypi 2021.9.4 requires numpy>=1.19, but you have numpy 1.14.5 which is incompatible.
Successfully installed numpy-1.14.5
```

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron,
It so happens that after installing tensorflow 1.9 instead of 1.10, the model worked. I hadn't tried this option before because changing tensorflow versions in other models required updating the code too.

Following a discussion with @miquelduranfrigola and Ankit during today's weekly meeting, they advised that I change tensorflow to another version provided it's < tensorflow=2.0(it's tensorflow 2.0+ that require updating the code)

So, after installing tensorflow=1.9.0, the model works locally using both run.sh and within ersilia(`using --repo_path`)

For both cases,  the model can't process some of the smiles, especially the long ones and therefore doesn't provide output for them. Good thing, these are not discarded in any case, just that their output values are empty. They are the same smiles(both using run.sh and within ersilia) e.g 13th, 20th, 24th
```
NCC[C@H](O)C(=O)N[C@@H]1C[C@H](N)[C@@H](O[C@H]2O[C@H](CN)[C@@H](O)[C@H](O)[C@H]2O)[C@H](O)[C@H]1O[C@H]3O[C@H](CO)[C@@H](O)[C@H](N)[C@H]3O,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
C[C@H]1O[C@@H](O[C@@H]\2C[C@@H]3O[C@](O)(C[C@@H](O)C[C@@H](O)[C@H](O)CC[C@@H](O)C[C@@H](O)CC(=O)O[C@@H](C)[C@H](C)[C@H](O)[C@@H](C)\C=C/C=C\C=C/C=C\C=C/C=C\C=C2)C[C@H](O)[C@H]3C(O)=O)[C@@H](O)[C@@H](N)[C@@H]1O,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```
Test file: [eml_50.csv](https://github.com/ersilia-os/eos7a04/files/12022927/eml_50.csv)
Run.sh Output: [output.csv](https://github.com/ersilia-os/eos7a04/files/12022979/output.csv)

👍 Model eos7a04 fetched successfully! [eos7a04_fetch_repo.log](https://github.com/ersilia-os/eos7a04/files/12022912/eos7a04_fetch_repo.log)
Ersilia CLI Output: [7a04_cli_output.csv](https://github.com/ersilia-os/eos7a04/files/12022954/7a04_cli_output.csv)
```
(ersilia) hellenah@hellenah-elitebook:~$ ersilia serve eos7a04
🚀 Serving model eos7a04: cdd-descriptor

   URL: http://127.0.0.1:38421/
   PID: 67458
   SRV: conda

👉 To run model:
   - run

💁 Information:
   - info
(ersilia) hellenah@hellenah-elitebook:~$ ersilia run -i "Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1"
{
    "input": {
        "key": "MCGSCOLBFJQGHM-SCZZXKLOSA-N",
        "input": "Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1",
        "text": "Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1"
    },
    "output": {
        "embedding": [
            -0.009983158,
            -0.10566875,
            0.29701394,
            -0.30282348,
            0.35138515,
            0.23139034,
            -0.3573404,
            -0.06484802,
            0.16204046,
...
```
For rdkit, even after specifying 2021.9.4. When I pushed and created the [PR](https://github.com/ersilia-os/eos7a04/pull/7), the Model Test on PR action [fails ](https://github.com/ersilia-os/eos7a04/actions/runs/5526928329/jobs/10082171366?pr=7#step:8:893).There isn't a specific error. Though, it's installing rdkit twice, and for the second time, it's installing in python3.10, not in the [model env ](https://github.com/ersilia-os/eos7a04/actions/runs/5526928329/jobs/10082171366?pr=7#step:8:659)with 3.6 which is already in the docker file.
```
Collecting rdkit-pypi==2021.9.4
  Downloading rdkit_pypi-2021.9.4-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20.6 MB)
```
and
```
Collecting rdkit-pypi
  Downloading rdkit_pypi-2022.9.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.4/29.4 MB 51.8 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/share/miniconda/lib/python3.10/site-packages (from rdkit-pypi) (1.25.1)
```

**Comment by GemmaTuron** [comment]
Hi @HellenNamulinda 

Thanks for the work and the explanations, it makes sense.
Do not worry about the long smiles, they cannot be parsed by the model. About the action failing, I have re run it because Ersilia was failing, seems ok now!

**Comment by HellenNamulinda** [comment]
Thanks @GemmaTuron,

I have checked the github actions. Though at the step of build and push when uploading to docker hub, it [fails](https://github.com/ersilia-os/eos7a04/actions/runs/5529277659/jobs/10087119415#step:7:127869) for both amd64 and arm64 with `This step has been truncated due to its large size.`

However, the build for only amd64 step succeeded. So, we have the docker image for amd64 only.
